<?php
require_once 'common/config.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

$mode = isset($_GET['mode']) && in_array($_GET['mode'], ['ai', 'hotseat']) ? $_GET['mode'] : 'hotseat';

require_once 'common/header.php';
?>

<div class="flex flex-col lg:flex-row items-center lg:items-start justify-center gap-8">
    <!-- Chessboard -->
    <div id="chessboard" class="grid grid-cols-8 grid-rows-8 w-full max-w-[400px] md:max-w-[600px] aspect-square shadow-2xl">
        <!-- Squares will be generated by JS -->
    </div>

    <!-- Game Info & Controls -->
    <div class="w-full lg:w-1/3 card p-6 rounded-lg">
        <h2 class="text-2xl font-bold mb-4 border-b border-gray-600 pb-2">Game Info</h2>
        <div id="status-area" class="text-xl font-semibold mb-4 p-3 bg-gray-900 rounded-md text-center">
            White's Turn
        </div>
        
        <div id="game-controls">
             <button id="new-game-btn" class="w-full btn-primary font-bold py-2 px-4 rounded-md mb-3">
                <i class="fa-solid fa-plus mr-2"></i>New Game
            </button>
            <button id="resign-btn" class="w-full btn-secondary font-bold py-2 px-4 rounded-md">
                <i class="fa-solid fa-flag mr-2"></i>Resign
            </button>
        </div>

        <!-- Hidden form for saving game -->
        <div id="save-game-section" class="hidden mt-6 text-center">
            <h3 class="text-lg font-bold mb-3">Game Over!</h3>
            <form action="profile.php" method="POST">
                <input type="hidden" id="game-result" name="result">
                <input type="hidden" id="game-opponent" name="opponent" value="<?= htmlspecialchars($mode) ?>">
                <input type="hidden" id="game-moves" name="moves">
                <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md">
                    <i class="fa-solid fa-save mr-2"></i>Save Game & Exit
                </button>
            </form>
             <a href="index.php" class="inline-block mt-3 text-sm text-gray-400 hover:text-white">Don't Save & Exit</a>
        </div>
    </div>
</div>

<?php
require_once 'common/bottom.php';
?>